nohup python3 ppo_train_baseline.py -en SawyerDoor-v0 -r 0 -g 1 -n 50 -sn True > logs/sawyer1.txt &
nohup python3 ppo_train_baseline.py -en SawyerDoor-v0 -r 2 -g 2 -n 50 -sn True > logs/sawyer2.txt &
nohup python3 ppo_train_baseline.py -en SawyerDoor-v0 -r 4 -g 3 -n 50 -sn True > logs/sawyer3.txt &
nohup python3 ppo_train_baseline.py -en SawyerDoor-v0 -r 6 -g 4 -n 50 -sn True > logs/sawyer4.txt &
nohup python3 ppo_train_baseline.py -en SawyerDoor-v0 -r 8 -g 5 -n 50 -sn True > logs/sawyer5.txt &
nohup python3 ppo_train_baseline.py -en Point2D-FourRoom-v1 -r 0 -g 6 -n 50 -sn True > logs/point2d1.txt &
nohup python3 ppo_train_baseline.py -en Point2D-FourRoom-v1 -r 2 -g 7 -n 50 -sn True > logs/point2d2.txt &
nohup python3 ppo_train_baseline.py -en Point2D-FourRoom-v1 -r 4 -g 8 -n 50 -sn True > logs/point2d3.txt &
nohup python3 ppo_train_baseline.py -en Point2D-FourRoom-v1 -r 6 -g 9 -n 50 -sn True > logs/point2d4.txt &
nohup python3 ppo_train_baseline.py -en Point2D-FourRoom-v1 -r 8 -g 10 -n 50 -sn True > logs/point2d5.txt &
nohup python3 ppo_train_baseline.py -en Point2DLargeEnv-v1 -r 0 -g 11 -n 50 -sn True > logs/pointlarge1.txt &
nohup python3 ppo_train_baseline.py -en Point2DLargeEnv-v1 -r 2 -g 12 -n 50 -sn True > logs/pointlarge2.txt &
nohup python3 ppo_train_baseline.py -en Point2DLargeEnv-v1 -r 4 -g 13 -n 50 -sn True > logs/pointlarge3.txt &
nohup python3 ppo_train_baseline.py -en Point2DLargeEnv-v1 -r 6 -g 14 -n 50 -sn True > logs/pointlarge4.txt &
nohup python3 ppo_train_baseline.py -en Point2DLargeEnv-v1 -r 8 -g 15 -n 50 -sn True > logs/pointlarge5.txt &
nohup python3 ppo_train_baseline.py -en FetchReach-v1 -r 0 -g 0 -n 50 -sn True > logs/fetchreach1.txt &
nohup python3 ppo_train_baseline.py -en FetchReach-v1 -r 2 -g 0 -n 50 -sn True > logs/fetchreach2.txt &
nohup python3 ppo_train_baseline.py -en FetchReach-v1 -r 4 -g 1 -n 50 -sn True > logs/fetchreach3.txt &
nohup python3 ppo_train_baseline.py -en FetchReach-v1 -r 6 -g 2 -n 50 -sn True > logs/fetchreach4.txt &
nohup python3 ppo_train_baseline.py -en FetchReach-v1 -r 8 -g 3 -n 50 -sn True > logs/fetchreach5.txt &
nohup python3 ppo_train_baseline.py -en SawyerReachXYZEnv-v1 -r 0 -g 4 -n 50 -sn True > logs/sawyerxyz1.txt &
nohup python3 ppo_train_baseline.py -en SawyerReachXYZEnv-v1 -r 2 -g 5 -n 50 -sn True > logs/sawyerxyz2.txt &
nohup python3 ppo_train_baseline.py -en SawyerReachXYZEnv-v1 -r 4 -g 6 -n 50 -sn True > logs/sawyerxyz3.txt &
nohup python3 ppo_train_baseline.py -en SawyerReachXYZEnv-v1 -r 6 -g 7 -n 50 -sn True > logs/sawyerxyz4.txt &
nohup python3 ppo_train_baseline.py -en SawyerReachXYZEnv-v1 -r 8 -g 8 -n 50 -sn True > logs/sawyerxyz5.txt &
nohup python3 ppo_train_baseline.py -en Reacher-v2 -r 0 -g 9 -n 50 -sn True > logs/reacher1.txt &
nohup python3 ppo_train_baseline.py -en Reacher-v2 -r 2 -g 10 -n 50 -sn True > logs/reacher2.txt &
nohup python3 ppo_train_baseline.py -en Reacher-v2 -r 4 -g 11 -n 50 -sn True > logs/reacher3.txt &
nohup python3 ppo_train_baseline.py -en Reacher-v2 -r 6 -g 12 -n 50 -sn True > logs/reacher4.txt &
nohup python3 ppo_train_baseline.py -en Reacher-v2 -r 8 -g 13 -n 50 -sn True > logs/reacher5.txt &
