nohup python3 ppo_train_baseline.py -en SawyerDoor-v0 -r 0 > logs/sawyer1.txt &
nohup python3 ppo_train_baseline.py -en SawyerDoor-v0 -r 2 > logs/sawyer2.txt &
nohup python3 ppo_train_baseline.py -en SawyerDoor-v0 -r 4 > logs/sawyer3.txt &
nohup python3 ppo_train_baseline.py -en SawyerDoor-v0 -r 6 > logs/sawyer4.txt &
nohup python3 ppo_train_baseline.py -en SawyerDoor-v0 -r 8 > logs/sawyer5.txt &
nohup python3 ppo_train_baseline.py -en Point2D-FourRoom-v1 -r 0 > logs/point2d1.txt &
nohup python3 ppo_train_baseline.py -en Point2D-FourRoom-v1 -r 2 > logs/point2d2.txt &
nohup python3 ppo_train_baseline.py -en Point2D-FourRoom-v1 -r 4 > logs/point2d3.txt &
nohup python3 ppo_train_baseline.py -en Point2D-FourRoom-v1 -r 6 > logs/point2d4.txt &
nohup python3 ppo_train_baseline.py -en Point2D-FourRoom-v1 -r 8 > logs/point2d5.txt &
nohup python3 ppo_train_baseline.py -en Point2DLargeEnv-v1 -r 0 > logs/pointlarge1.txt &
nohup python3 ppo_train_baseline.py -en Point2DLargeEnv-v1 -r 2 > logs/pointlarge2.txt &
nohup python3 ppo_train_baseline.py -en Point2DLargeEnv-v1 -r 4 > logs/pointlarge3.txt &
nohup python3 ppo_train_baseline.py -en Point2DLargeEnv-v1 -r 6 > logs/pointlarge4.txt &
nohup python3 ppo_train_baseline.py -en Point2DLargeEnv-v1 -r 8 > logs/pointlarge5.txt &
nohup python3 ppo_train_baseline.py -en FetchReach-v1 -r 0 > logs/fetchreach1.txt &
nohup python3 ppo_train_baseline.py -en FetchReach-v1 -r 2 > logs/fetchreach2.txt &
nohup python3 ppo_train_baseline.py -en FetchReach-v1 -r 4 > logs/fetchreach3.txt &
nohup python3 ppo_train_baseline.py -en FetchReach-v1 -r 6 > logs/fetchreach4.txt &
nohup python3 ppo_train_baseline.py -en FetchReach-v1 -r 8 > logs/fetchreach5.txt &
nohup python3 ppo_train_baseline.py -en SawyerReachXYZEnv-v1 -r 0 > logs/sawyerxyz1.txt &
nohup python3 ppo_train_baseline.py -en SawyerReachXYZEnv-v1 -r 2 > logs/sawyerxyz2.txt &
nohup python3 ppo_train_baseline.py -en SawyerReachXYZEnv-v1 -r 4 > logs/sawyerxyz3.txt &
nohup python3 ppo_train_baseline.py -en SawyerReachXYZEnv-v1 -r 6 > logs/sawyerxyz4.txt &
nohup python3 ppo_train_baseline.py -en SawyerReachXYZEnv-v1 -r 8 > logs/sawyerxyz5.txt &
nohup python3 ppo_train_baseline.py -en Reacher-v2 -r 0 > logs/reacher1.txt &
nohup python3 ppo_train_baseline.py -en Reacher-v2 -r 2 > logs/reacher2.txt &
nohup python3 ppo_train_baseline.py -en Reacher-v2 -r 4 > logs/reacher3.txt &
nohup python3 ppo_train_baseline.py -en Reacher-v2 -r 6 > logs/reacher4.txt &
nohup python3 ppo_train_baseline.py -en Reacher-v2 -r 8 > logs/reacher5.txt &
